// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq6nymvypFGg219mmf5x6qkNFxAiGec3A',
    appId: '1:513108903383:web:bfe931c7307f1c1ce8b792',
    messagingSenderId: '513108903383',
    projectId: 'moviles-3d240',
    authDomain: 'moviles-3d240.firebaseapp.com',
    storageBucket: 'moviles-3d240.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT1wN7OxL61P48zlvWI0FW8ZT4pRaWURM',
    appId: '1:513108903383:android:05b9844b5c47c891e8b792',
    messagingSenderId: '513108903383',
    projectId: 'moviles-3d240',
    storageBucket: 'moviles-3d240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3wDVjTGpsBoXs2_ErDEWkILeCGk-6y4',
    appId: '1:513108903383:ios:abfff32860fa26e7e8b792',
    messagingSenderId: '513108903383',
    projectId: 'moviles-3d240',
    storageBucket: 'moviles-3d240.appspot.com',
    iosClientId: '513108903383-l4s342e5fnnfd6k8vjbhvvnb7rv945qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw3wDVjTGpsBoXs2_ErDEWkILeCGk-6y4',
    appId: '1:513108903383:ios:abfff32860fa26e7e8b792',
    messagingSenderId: '513108903383',
    projectId: 'moviles-3d240',
    storageBucket: 'moviles-3d240.appspot.com',
    iosClientId: '513108903383-l4s342e5fnnfd6k8vjbhvvnb7rv945qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );
}
